
/* Drop Tables */

DROP TABLE AUTHOERS;
DROP TABLE COMMENTS;
DROP TABLE FAVORIT;
DROP TABLE USE_FLOWERS;
DROP TABLE FLOWERS;
DROP TABLE USE_TOOLS;
DROP TABLE TOOLS;
DROP TABLE USERS;




/* Create Tables */

CREATE TABLE IF NOT EXISTS USERS
(
	ID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	NICKNAME TEXT NOT NULL,
	AUTH_CODE TEXT DEFAULT '0' NOT NULL,
	BIRTHDAY TEXT DEFAULT 'null',
	IMAGE BLOB,
	CREATE_DATE TEXT,
	UPDATE_DATE TEXT
);


CREATE TABLE IF NOT EXISTS AUTHOERS
(
	ID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	USER_ID INTEGER DEFAULT 1 NOT NULL,
	NAME TEXT NOT NULL,
	IMAGE BLOB,
	LOCATE TEXT DEFAULT 'null',
	SCHOOL TEXT,
	STYLE TEXT,
	ORGAN_ID INTEGER DEFAULT null,
	USE_FLOWER_ID INTEGER DEFAULT null,
	USE_TOOL_ID INTEGER DEFAULT null,
	APPEAL TEXT DEFAULT 'null',
	CHECK_POINT TEXT DEFAULT 'null',
	CREATE_DATE TEXT DEFAULT 'null',
	UPDATE_DATE TEXT DEFAULT 'null',
	FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
);


CREATE TABLE IF NOT EXISTS COMMENTS
(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SERVER_AUTHOER_ID INTEGER NOT NULL,
	CONTENT TEXT
);


CREATE TABLE IF NOT EXISTS FAVORIT
(
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SERVER_AUTHOER_ID INTEGER NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS FLOWERS
(
	ID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	NAME_KANA TEXT NOT NULL,
	SEASON_MONTH NUMERIC NOT NULL,
	IMAGE BLOB
);


CREATE TABLE IF NOT EXISTS TOOLS
(
	ID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	IMAGE BLOB
);


CREATE TABLE IF NOT EXISTS USE_FLOWERS
(
	ID INTEGER NOT NULL,
	FLOWER_ID INTEGER NOT NULL,
	FOREIGN KEY (FLOWER_ID)
	REFERENCES FLOWERS (ID)
);


CREATE TABLE IF NOT EXISTS USE_TOOLS
(
	ID INTEGER,
	TOOL_ID INTEGER NOT NULL,
	FOREIGN KEY (TOOL_ID)
	REFERENCES TOOLS (ID)
);



